from __future__ import annotations

from typing import Any, Protocol

from fraud_engine.domain.enums import AlertStatus, RiskLevel
from fraud_engine.domain.models import (
    CustomerRiskProfile,
    FraudAlert,
    FraudRuleConfig,
    OutboxEvent,
    Transaction,
)


class TransactionRepository(Protocol):
    async def save(self, transaction: Transaction) -> None: ...
    async def get_by_id(self, transaction_id: str) -> Transaction | None: ...
    async def list(
        self,
        customer_id: str | None = None,
        category: str | None = None,
        min_amount: float | None = None,
        max_amount: float | None = None,
        start_date: str | None = None,
        end_date: str | None = None,
        is_flagged: bool | None = None,
        page: int = 1,
        page_size: int = 20,
        sort_by: str = "timestamp",
        order: str = "desc",
    ) -> tuple[list[Transaction], int]: ...
    async def get_recent(
        self, customer_id: str, limit: int = 100, hours: int = 24
    ) -> list[Transaction]: ...
    async def flag(self, transaction_id: str) -> None: ...


class RuleRepository(Protocol):
    async def save(self, rule: FraudRuleConfig) -> None: ...
    async def get_by_id(self, rule_id: str) -> FraudRuleConfig | None: ...
    async def list_all(self) -> list[FraudRuleConfig]: ...
    async def list_enabled(self) -> list[FraudRuleConfig]: ...
    async def update(self, rule: FraudRuleConfig) -> None: ...
    async def delete(self, rule_id: str) -> None: ...


class AlertRepository(Protocol):
    async def save(self, alert: FraudAlert) -> None: ...
    async def save_many(self, alerts: list[FraudAlert]) -> None: ...
    async def get_by_id(self, alert_id: str) -> FraudAlert | None: ...
    async def list(
        self,
        status: AlertStatus | None = None,
        severity: RiskLevel | None = None,
        customer_id: str | None = None,
        rule_type: str | None = None,
        start_date: str | None = None,
        end_date: str | None = None,
        page: int = 1,
        page_size: int = 20,
        sort_by: str = "created_at",
        order: str = "desc",
    ) -> tuple[list[FraudAlert], int]: ...
    async def update_status(self, alert_id: str, status: AlertStatus) -> None: ...
    async def get_by_transaction(self, transaction_id: str) -> list[FraudAlert]: ...
    async def get_summary(self) -> dict[str, Any]: ...
    async def get_by_customer(
        self, customer_id: str, page: int = 1, page_size: int = 20
    ) -> tuple[list[FraudAlert], int]: ...


class CustomerRepository(Protocol):
    async def get_profile(self, customer_id: str) -> CustomerRiskProfile | None: ...
    async def upsert_profile(self, profile: CustomerRiskProfile) -> None: ...
    async def get_high_risk(self, limit: int = 10) -> list[CustomerRiskProfile]: ...


class OutboxRepository(Protocol):
    async def save(self, event: OutboxEvent) -> None: ...
    async def get_unpublished(self, limit: int = 50) -> list[OutboxEvent]: ...
    async def mark_published(self, event_id: str) -> None: ...


class EventBus(Protocol):
    async def publish(self, event_type: str, payload: dict[str, Any]) -> None: ...
    async def start_consuming(self) -> None: ...
    async def stop_consuming(self) -> None: ...


class CachePort(Protocol):
    async def get(self, key: str) -> str | None: ...
    async def set(self, key: str, value: str, ttl_seconds: int = 300) -> None: ...
    async def delete(self, key: str) -> None: ...
    async def increment(self, key: str, ttl_seconds: int = 60) -> int: ...


class StoragePort(Protocol):
    async def put(self, key: str, data: bytes, content_type: str = "application/json") -> None: ...
    async def get(self, key: str) -> bytes | None: ...
